# Generated by Django 4.2.25 on 2025-11-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leggitaliano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordtype',
            name='cn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wordtype',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
