# Generated by Django 4.2.25 on 2025-10-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leggitaliano', '0002_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user_id',
            new_name='user',
        ),
    ]
