# Generated by Django 4.2.25 on 2025-11-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leggitaliano', '0002_wordtype_cn_wordtype_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verb',
            name='condizionale',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='congiuntivo_imperfetto',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='congiuntivo_presente',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='futuro',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='gerundio',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='imperativo',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='imperfetto',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='passato_remoto',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='perfetto',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='presente',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verb',
            name='values',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
