# Generated by Django 4.2.25 on 2025-10-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leggitaliano', '0003_rename_user_id_article_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.CharField(max_length=255)),
                ('translation', models.CharField(blank=True, max_length=255, null=True)),
                ('presente', models.CharField(blank=True, max_length=255, null=True)),
                ('perfetto', models.CharField(blank=True, max_length=255, null=True)),
                ('gerundio', models.CharField(blank=True, max_length=255, null=True)),
                ('imperfetto', models.CharField(blank=True, max_length=255, null=True)),
                ('passato_remoto', models.CharField(blank=True, max_length=255, null=True)),
                ('futuro', models.CharField(blank=True, max_length=255, null=True)),
                ('congiuntivo_presente', models.CharField(blank=True, max_length=255, null=True)),
                ('congiuntivo_imperfetto', models.CharField(blank=True, max_length=255, null=True)),
                ('condizionale', models.CharField(blank=True, max_length=255, null=True)),
                ('imperativo', models.CharField(blank=True, max_length=255, null=True)),
                ('values', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
