# Generated by Django 4.2.25 on 2025-12-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leggitaliano', '0003_alter_verb_condizionale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verb',
            old_name='futuro',
            new_name='indicativo_futuro',
        ),
        migrations.RenameField(
            model_name='verb',
            old_name='imperfetto',
            new_name='indicativo_imperfetto',
        ),
        migrations.RenameField(
            model_name='verb',
            old_name='passato_remoto',
            new_name='indicativo_passato_remoto',
        ),
        migrations.RenameField(
            model_name='verb',
            old_name='presente',
            new_name='indicativo_presente',
        ),
    ]
