# Generated by Django 4.2.25 on 2025-10-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leggitaliano', '0004_verb'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
