# Generated by Django 4.2.25 on 2025-12-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leggitaliano', '0004_rename_futuro_verb_indicativo_futuro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='participio_passato',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verb',
            name='participio_presente',
            field=models.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
