# Generated by Django 4.2.25 on 2025-12-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leggitaliano', '0005_verb_participio_passato_verb_participio_presente'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryword',
            name='is_inherit_translations',
            field=models.BooleanField(default=False),
        ),
    ]
