# Generated by Django 4.2.25 on 2025-10-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leggitaliano', '0005_wordtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('source_lang', models.CharField(db_index=True, max_length=255)),
                ('target_lang', models.CharField(db_index=True, max_length=255)),
            ],
        ),
    ]
