# Generated by Django 4.2.25 on 2025-10-29 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leggitaliano', '0006_dictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='source_lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_dicts', to='leggitaliano.language'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='target_lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_dicts', to='leggitaliano.language'),
        ),
    ]
