# Generated by Django 4.2.25 on 2025-12-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leggitaliano', '0006_dictionaryword_is_inherit_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryword',
            name='is_inherit_notes',
            field=models.BooleanField(default=False),
        ),
    ]
