# Generated by Django 4.2.25 on 2026-02-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leggitaliano', '0007_dictionaryword_is_inherit_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='current_page',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
