# Generated by Django 4.2.25 on 2025-10-31 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leggitaliano', '0008_dictionaryword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DictionaryWord',
        ),
    ]
