# Generated by Django 4.2.25 on 2025-10-30 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leggitaliano', '0008_dictionaryword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DictionaryWord',
        ),
    ]
