# Generated by Django 4.2.25 on 2025-11-01 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leggitaliano', '0012_dictionaryword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaryword',
            name='notes',
        ),
    ]
