# Generated by Django 4.2.25 on 2025-11-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leggitaliano', '0013_remove_dictionaryword_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryword',
            name='notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
