# Generated by Django 4.2.25 on 2025-11-02 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leggitaliano', '0014_dictionaryword_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(blank=True)),
                ('translation', models.TextField(blank=True, null=True)),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentences', to='leggitaliano.dictionaryword')),
            ],
        ),
    ]
